{
  "uid" : "9c51532c30690e1c",
  "name" : "create PG datasource with form",
  "fullName" : "test_datasource.TestDataSource#test_postgres",
  "historyId" : "c237dd82ddad2feda3f10d0d2ed5220a",
  "time" : {
    "start" : 1666094823837,
    "stop" : 1666094834017,
    "duration" : 10180
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert 'invalid' == 'ready'\n  - ready\n  + invalid",
  "statusTrace" : "self = <test.test_datasource.TestDataSource object at 0x7f4ab4c62990>\n\n    @allure.title(\"create PG datasource with form\")\n    def test_postgres(self):\n        host, port = env['postgres.HOST'].split(\":\")\n        test_ds = DataSource(\"postgresql\", f\"test_postgres_{random_str()}\")\n        test_ds.host(host).database(env['postgres.DB']).user(env['postgres.USERNAME']) \\\n            .password(env['postgres.PASSWORD']).schema(\"admin\").port(int(port))\n        assert test_ds.save()\n        assert test_ds.validate()\n>       assert test_ds.status() == \"ready\"\nE       AssertionError: assert 'invalid' == 'ready'\nE         - ready\nE         + invalid\n\ntest_datasource.py:59: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert 'invalid' == 'ready'\n  - ready\n  + invalid",
    "statusTrace" : "self = <test.test_datasource.TestDataSource object at 0x7f4ab4c62990>\n\n    @allure.title(\"create PG datasource with form\")\n    def test_postgres(self):\n        host, port = env['postgres.HOST'].split(\":\")\n        test_ds = DataSource(\"postgresql\", f\"test_postgres_{random_str()}\")\n        test_ds.host(host).database(env['postgres.DB']).user(env['postgres.USERNAME']) \\\n            .password(env['postgres.PASSWORD']).schema(\"admin\").port(int(port))\n        assert test_ds.save()\n        assert test_ds.validate()\n>       assert test_ds.status() == \"ready\"\nE       AssertionError: assert 'invalid' == 'ready'\nE         - ready\nE         + invalid\n\ntest_datasource.py:59: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "b602eadea43579b5",
      "name" : "stdout",
      "source" : "b602eadea43579b5.txt",
      "type" : "text/plain",
      "size" : 824
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "datasource"
  }, {
    "name" : "suite",
    "value" : "test_datasource"
  }, {
    "name" : "subSuite",
    "value" : "TestDataSource"
  }, {
    "name" : "host",
    "value" : "436f84806f7e"
  }, {
    "name" : "thread",
    "value" : "889-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_datasource"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "e93325df6b982f8a",
        "status" : "failed",
        "statusDetails" : "AssertionError: assert 'invalid' == 'ready'\n  - ready\n  + invalid",
        "time" : {
          "start" : 1666090860819,
          "stop" : 1666090870985,
          "duration" : 10166
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "9c51532c30690e1c.json",
  "parameterValues" : [ ]
}